### ISSUE TITLE
I met some environment problem when I used  conda install --yes --file requirements.txt

### ISSUE THREAD

**Issue by liguoyu666** [TreB1eN/InsightFace_Pytorch#126]
It's python3.6 on ubuntu16

Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - mxnet==1.2.1.post1
  - opencv_python==3.4.0.12
  - easydict==1.7
  - scikit_learn==0.19.2
  - mxnet_cu90==1.2.1
  - torch==0.4.0

Current channels:

  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/linux-64
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/noarch
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

and it is the same problem on windows.
could you help me?

**Comment by tjulitianyi1997** [comment]
It is recommended to use the `` pip '' command to install

**Comment by liguoyu666** [comment]
> It is recommended to use the `` pip '' command to install

Thank you, I was able to run the infer_on_video.py.

**Comment by tjulitianyi1997** [comment]
Hello, can you achieve the effect of the author on youtobe? Enter a video, can you output a video that can be played? Tianyi Li 邮箱：tjulitianyi1997@gmail.com 签名由 网易邮箱大师 定制 On 03/06/2020 18:17, 大禹 wrote: It is recommended to use the `` pip '' command to install Thank you, I was able to run the infer_on_video.py. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by liguoyu666** [comment]
> Hello, can you achieve the effect of the author on youtobe? Enter a video, can you output a video that can be played? Tianyi Li 邮箱：tjulitianyi1997@gmail.com 签名由 网易邮箱大师 定制 On 03/06/2020 18:17, 大禹 wrote: It is recommended to use the `` pip '' command to install Thank you, I was able to run the infer_on_video.py. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

可以的，兄弟。你是输出来的视频显示为0kb或几kb吗？我之前遇到这个问题了，应该是作者的代码有问题，我把读取视频和写入视频的代码改成我以前用的就没问题了

**Comment by tjulitianyi1997** [comment]
噢噢，是的，只有几KB，非常感谢，您能分享一下写视频的部分吗？我刚刚接触，这是我第一个项目，没想到出师不利。总之很感谢。 Tianyi Li 邮箱：tjulitianyi1997@gmail.com 签名由 网易邮箱大师 定制 On 03/06/2020 20:25, 大禹 wrote: Hello, can you achieve the effect of the author on youtobe? Enter a video, can you output a video that can be played? Tianyi Li 邮箱：tjulitianyi1997@gmail.com 签名由 网易邮箱大师 定制 On 03/06/2020 18:17, 大禹 wrote: It is recommended to use the `` pip '' command to install Thank you, I was able to run the infer_on_video.py. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 可以的，兄弟。你是输出来的视频显示为0kb或几kb吗？我之前遇到这个问题了，应该是作者的代码有问题，我把读取视频和写入视频的代码改成我以前用的就没问题了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by liguoyu666** [comment]
视频文件放在data/test_video文件夹下，直接运行即可

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tianyi Li"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月6日(星期五) 晚上9:19
收件人:&nbsp;"TreB1eN/InsightFace_Pytorch"<InsightFace_Pytorch@noreply.github.com&gt;;
抄送:&nbsp;"风雨如晦"<1085032365@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [TreB1eN/InsightFace_Pytorch] I met some environment problem when I used  conda install --yes --file requirements.txt (#126)



噢噢，是的，只有几KB，非常感谢，您能分享一下写视频的部分吗？我刚刚接触，这是我第一个项目，没想到出师不利。总之很感谢。 Tianyi Li 邮箱：tjulitianyi1997@gmail.com 签名由 网易邮箱大师 定制 On 03/06/2020 20:25, 大禹 wrote: Hello, can you achieve the effect of the author on youtobe? Enter a video, can you output a video that can be played? Tianyi Li 邮箱：tjulitianyi1997@gmail.com 签名由 网易邮箱大师 定制 On 03/06/2020 18:17, 大禹 wrote: It is recommended to use the `` pip '' command to install Thank you, I was able to run the infer_on_video.py. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 可以的，兄弟。你是输出来的视频显示为0kb或几kb吗？我之前遇到这个问题了，应该是作者的代码有问题，我把读取视频和写入视频的代码改成我以前用的就没问题了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by tjulitianyi1997** [comment]
您好，我不太清楚 视频文件放在data/test_video文件夹下，直接运行即可  这句话什么意思，因为作者是放在facebank文件夹下，而且对于他的代码，我不知道如何修改，您能说清楚一下吗？ 我的QQ是1375088614，或者您可以联系我QQ邮箱，谢谢。 Tianyi Li 邮箱：tjulitianyi1997@gmail.com 签名由 网易邮箱大师 定制 On 03/06/2020 21:53, 大禹 wrote: 视频文件放在data/test_video文件夹下，直接运行即可 &nbsp; ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Tianyi Li"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月6日(星期五) 晚上9:19 收件人:&nbsp;"TreB1eN/InsightFace_Pytorch"<InsightFace_Pytorch@noreply.github.com&gt;; 抄送:&nbsp;"风雨如晦"<1085032365@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;; 主题:&nbsp;Re: [TreB1eN/InsightFace_Pytorch] I met some environment problem when I used conda install --yes --file requirements.txt (#126) 噢噢，是的，只有几KB，非常感谢，您能分享一下写视频的部分吗？我刚刚接触，这是我第一个项目，没想到出师不利。总之很感谢。 Tianyi Li 邮箱：tjulitianyi1997@gmail.com 签名由 网易邮箱大师 定制 On 03/06/2020 20:25, 大禹 wrote: Hello, can you achieve the effect of the author on youtobe? Enter a video, can you output a video that can be played? Tianyi Li 邮箱：tjulitianyi1997@gmail.com 签名由 网易邮箱大师 定制 On 03/06/2020 18:17, 大禹 wrote: It is recommended to use the `` pip '' command to install Thank you, I was able to run the infer_on_video.py. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 可以的，兄弟。你是输出来的视频显示为0kb或几kb吗？我之前遇到这个问题了，应该是作者的代码有问题，我把读取视频和写入视频的代码改成我以前用的就没问题了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by liguoyu666** [comment]
我修改了他的代码，视频文件放在data/test_video 文件夹下，再运行infer_on_video，生成的视频会保存在data/output文件夹下，其他的代码还是按作者的方法处理，你运行一次，能跑通就好了。报错的话，就按报错提示找问题。我就是用邮箱回你消息的啊&nbsp;


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tianyi Li"<notifications@github.com&gt;; 
发送时间: 2020年3月6日(星期五) 晚上10:10
收件人: "TreB1eN/InsightFace_Pytorch"<InsightFace_Pytorch@noreply.github.com&gt;; 
抄送: "风雨如晦"<1085032365@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [TreB1eN/InsightFace_Pytorch] I met some environment problem when I used  conda install --yes --file requirements.txt (#126)



您好，我不太清楚 视频文件放在data/test_video文件夹下，直接运行即可&nbsp; 这句话什么意思，因为作者是放在facebank文件夹下，而且对于他的代码，我不知道如何修改，您能说清楚一下吗？ 我的QQ是1375088614，或者您可以联系我QQ邮箱，谢谢。 Tianyi Li 邮箱：tjulitianyi1997@gmail.com 签名由 网易邮箱大师 定制 On 03/06/2020 21:53, 大禹 wrote: 视频文件放在data/test_video文件夹下，直接运行即可 &amp;nbsp; ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人:&amp;nbsp;"Tianyi Li"<notifications@github.com&amp;gt;; 发送时间:&amp;nbsp;2020年3月6日(星期五) 晚上9:19 收件人:&amp;nbsp;"TreB1eN/InsightFace_Pytorch"<InsightFace_Pytorch@noreply.github.com&amp;gt;; 抄送:&amp;nbsp;"风雨如晦"<1085032365@qq.com&amp;gt;;"State change"<state_change@noreply.github.com&amp;gt;; 主题:&amp;nbsp;Re: [TreB1eN/InsightFace_Pytorch] I met some environment problem when I used conda install --yes --file requirements.txt (#126) 噢噢，是的，只有几KB，非常感谢，您能分享一下写视频的部分吗？我刚刚接触，这是我第一个项目，没想到出师不利。总之很感谢。 Tianyi Li 邮箱：tjulitianyi1997@gmail.com 签名由 网易邮箱大师 定制 On 03/06/2020 20:25, 大禹 wrote: Hello, can you achieve the effect of the author on youtobe? Enter a video, can you output a video that can be played? Tianyi Li 邮箱：tjulitianyi1997@gmail.com 签名由 网易邮箱大师 定制 On 03/06/2020 18:17, 大禹 wrote: It is recommended to use the `` pip '' command to install Thank you, I was able to run the infer_on_video.py. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 可以的，兄弟。你是输出来的视频显示为0kb或几kb吗？我之前遇到这个问题了，应该是作者的代码有问题，我把读取视频和写入视频的代码改成我以前用的就没问题了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by beibei1998** [comment]
> 我修改了他的代码，视频文件放在data/test_video 文件夹下，再运行infer_on_video，生成的视频会保存在data/output文件夹下，其他的代码还是按作者的方法处理，你运行一次，能跑通就好了。报错的话，就按报错提示找问题。我就是用邮箱回你消息的啊&nbsp; &nbsp;
> […](#)

你好，我更换了输入输出的位置为data/test_video和data/output，但保存的视频还是几k，请问还有其他地方需要修改的吗？

**Comment by ljjlarry** [comment]
您好,我输出的视频也只有几kb，请问能把修改的video代码发我一份吗，我的邮箱是277664198@qq.com。

**Comment by liguoyu666** [comment]
不好意思，原代码找不到了，我看了哈问题，你可以在网上搜索一下，用opencv读取视频，把视频分帧，再把每一帧送入模型检测，得到画框的每一帧图片，最后将它们合为视频，你有其他目标检测的代码的话，可以直接修改套用过来，网上很多这种代码的。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月8日(星期三) 晚上9:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [TreB1eN/InsightFace_Pytorch] I met some environment problem when I used  conda install --yes --file requirements.txt (#126)





 
***@***.***。
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
