### ISSUE TITLE
Some errors about image color 

### ISSUE THREAD

**Issue by lvvvmd** [TreB1eN/InsightFace_Pytorch#13]
Hi,
      Thanks for your great contribute on this open source work! But I have a few questions!
      Firstly, I downloaded the faces_webface_112x112.zip from InsightFace Dataset zoo. Then I unzipped
the data and followed your instruction to generate training imgs but I got such images!
![image](https://user-images.githubusercontent.com/26196355/47349373-194b7d80-d6e6-11e8-878a-a5d5e6d46aa8.png)
![image](https://user-images.githubusercontent.com/26196355/47349398-21a3b880-d6e6-11e8-98fc-2198ce1f4ec9.png)
      It looks like an issue about RGB channel and BGR channel. So i wonder whether its color is correct.
      Thank you!

**Comment by cvtower** [comment]
Hi all,

This is BGR format image, which is easy to verify.
All images under folder /faces_emore/imgs are BGR images too.

**Comment by JingyuanHu** [comment]
I'm confused too. All images under folder /faces_emore/imgs are BGR format and I dont find  the RGB transpose in this training code.  However,

**Comment by cvtower** [comment]
data_pipe.py +line 59
img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR).

**Comment by JingyuanHu** [comment]
Yeah, that's true. But it is different, right?  
1. Line59 in data_pipe.py is used for preprocessing data which is validation data such as lfw, cfp_fp. This operation can transform these data from rgb to bgr. So, that means the data used for networks is in BGR format.  
2. However, in face_verify.py, RGB data is used. It's strange, right?  It must be a transform in some place, but I dont find where it is.  
3. And I'm very sure that the data used for networks is RGB format, because the test results are very poor if I use a BGR format data as input.

That's why I'm confused.

**Comment by TreB1eN** [comment]
Hi, guys, after check on the codes, the conclusion is all the traning and evaluation image are all in bgr format, so the main codes are ok.
The problem is I shouldn't change the format during inference, so I have updated the following codes
image = Image.fromarray(frame[...,::-1]) #bgr to rgb
to:
image = Image.fromarray(frame) #bgr input format
in face_verify.py and infer_on_video.py

**Comment by JingyuanHu** [comment]
Got it, thank you @TreB1eN

**Comment by wanjinchang** [comment]
> Yeah, that's true. But it is different, right?
> 
> 1. Line59 in data_pipe.py is used for preprocessing data which is validation data such as lfw, cfp_fp. This operation can transform these data from rgb to bgr. So, that means the data used for networks is in BGR format.
> 2. However, in face_verify.py, RGB data is used. It's strange, right?  It must be a transform in some place, but I dont find where it is.
> 
> That's why I'm confused.

Line92 in data_pipe.py is used for saving face images which used for training in RGB format. So, that means the data used for training is in RGB format???!!!
